// Generated by gencpp from file TBrain/4vec.msg
// DO NOT EDIT!


#ifndef TBRAIN_MESSAGE_4VEC_H
#define TBRAIN_MESSAGE_4VEC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace TBrain
{
template <class ContainerAllocator>
struct 4vec_
{
  typedef 4vec_<ContainerAllocator> Type;

  4vec_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , w(0.0)  {
    }
  4vec_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::TBrain::4vec_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::TBrain::4vec_<ContainerAllocator> const> ConstPtr;

}; // struct 4vec_

typedef ::TBrain::4vec_<std::allocator<void> > 4vec;

typedef boost::shared_ptr< ::TBrain::4vec > 4vecPtr;
typedef boost::shared_ptr< ::TBrain::4vec const> 4vecConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::TBrain::4vec_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::TBrain::4vec_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::TBrain::4vec_<ContainerAllocator1> & lhs, const ::TBrain::4vec_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.w == rhs.w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::TBrain::4vec_<ContainerAllocator1> & lhs, const ::TBrain::4vec_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace TBrain

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::TBrain::4vec_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::TBrain::4vec_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::TBrain::4vec_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::TBrain::4vec_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::TBrain::4vec_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::TBrain::4vec_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::TBrain::4vec_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a779879fadf0160734f906b8c19c7004";
  }

  static const char* value(const ::TBrain::4vec_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa779879fadf01607ULL;
  static const uint64_t static_value2 = 0x34f906b8c19c7004ULL;
};

template<class ContainerAllocator>
struct DataType< ::TBrain::4vec_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TBrain/4vec";
  }

  static const char* value(const ::TBrain::4vec_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::TBrain::4vec_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::TBrain::4vec_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::TBrain::4vec_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct 4vec_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::TBrain::4vec_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::TBrain::4vec_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TBRAIN_MESSAGE_4VEC_H
