// Generated by gencpp from file TBrain/pose.msg
// DO NOT EDIT!


#ifndef TBRAIN_MESSAGE_POSE_H
#define TBRAIN_MESSAGE_POSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <TBrain/4vec.h>

namespace TBrain
{
template <class ContainerAllocator>
struct pose_
{
  typedef pose_<ContainerAllocator> Type;

  pose_()
    : header()
    , matrix()
    , other(0)  {
    }
  pose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , matrix(_alloc)
    , other(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::TBrain::4vec_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::TBrain::4vec_<ContainerAllocator> >::other >  _matrix_type;
  _matrix_type matrix;

   typedef uint8_t _other_type;
  _other_type other;





  typedef boost::shared_ptr< ::TBrain::pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::TBrain::pose_<ContainerAllocator> const> ConstPtr;

}; // struct pose_

typedef ::TBrain::pose_<std::allocator<void> > pose;

typedef boost::shared_ptr< ::TBrain::pose > posePtr;
typedef boost::shared_ptr< ::TBrain::pose const> poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::TBrain::pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::TBrain::pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::TBrain::pose_<ContainerAllocator1> & lhs, const ::TBrain::pose_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.matrix == rhs.matrix &&
    lhs.other == rhs.other;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::TBrain::pose_<ContainerAllocator1> & lhs, const ::TBrain::pose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace TBrain

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::TBrain::pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::TBrain::pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::TBrain::pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::TBrain::pose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::TBrain::pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::TBrain::pose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::TBrain::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "610b28f21dd689a9c2eec18803824590";
  }

  static const char* value(const ::TBrain::pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x610b28f21dd689a9ULL;
  static const uint64_t static_value2 = 0xc2eec18803824590ULL;
};

template<class ContainerAllocator>
struct DataType< ::TBrain::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TBrain/pose";
  }

  static const char* value(const ::TBrain::pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::TBrain::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"TBrain/4vec[] matrix\n"
"uint8 other\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: TBrain/4vec\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::TBrain::pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::TBrain::pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.matrix);
      stream.next(m.other);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::TBrain::pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::TBrain::pose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "matrix[]" << std::endl;
    for (size_t i = 0; i < v.matrix.size(); ++i)
    {
      s << indent << "  matrix[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::TBrain::4vec_<ContainerAllocator> >::stream(s, indent + "    ", v.matrix[i]);
    }
    s << indent << "other: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.other);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TBRAIN_MESSAGE_POSE_H
